# -*- coding: utf-8 -*-
"""Soal_1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKbfYwrJxacxkwQ0x2YXZgITKJnHbX3o
"""

!pip install experta

!pip install --upgrade frozendict

# -*- coding: utf-8 -*-
"""Soal_1 - Sistem Pakar Hama Tanaman

Menggunakan library experta.
"""

from experta import *

class DiagnosisHama(KnowledgeEngine):

    @Rule(Fact(daun_menguning=True) & Fact(tanaman_layu=True))
    def virus_tanaman(self):
        print("Diagnosis: Tanaman kemungkinan terkena Virus Tanaman.")

    @Rule(Fact(daun_menguning=True))
    def kutu_daun(self):
        print("Diagnosis: Tanaman kemungkinan terkena Hama Kutu Daun.")

    @Rule(Fact(terdapat_bercak_hitam=True))
    def jamur_daun(self):
        print("Diagnosis: Tanaman kemungkinan terkena Jamur Daun.")

    @Rule(Fact(daun_berlubang=True))
    def hama_ulat(self):
        print("Diagnosis: Tanaman kemungkinan terkena Hama Ulat.")

    @Rule(Fact(tanaman_layu=True))
    def infeksi_bakteri(self):
        print("Diagnosis: Tanaman kemungkinan terkena Infeksi Bakteri.")

    @Rule(Fact(daun_menguning=False) & Fact(terdapat_bercak_hitam=False) & Fact(daun_berlubang=False) & Fact(tanaman_layu=False))
    def sehat(self):
        print("Diagnosis: Tanaman tampak sehat.")

def get_input():
    """Fungsi bantu untuk mendapatkan input dari pengguna."""
    def tanya(pertanyaan):
        return input(pertanyaan + " (ya/tidak): ").strip().lower() == "ya"

    return {
        "daun_menguning": tanya("Apakah daun tanaman menguning?"),
        "terdapat_bercak_hitam": tanya("Apakah terdapat bercak hitam pada daun?"),
        "daun_berlubang": tanya("Apakah daun tanaman berlubang?"),
        "tanaman_layu": tanya("Apakah tanaman terlihat layu?"),
    }

# Menjalankan Sistem Pakar
if __name__ == "__main__":
    gejala = get_input()
    sistem = DiagnosisHama()
    sistem.reset()

    for g, ada in gejala.items():
        sistem.declare(Fact(**{g: ada}))

    sistem.run()